vich_uploader:
    db_driver: orm

    mappings:
        product_illustrations:
            uri_prefix: '%app.path.product_illustrations%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_illustrations%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
